version: "3.7"
services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: reverse-proxy
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - rolling_network

  api:
    depends_on:
      - reverse-proxy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-rolling-update
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: "unless-stopped"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rolling_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.entrypoints=insecure"

networks:
  rolling_network:
    external: true
