entryPoints:
  insecure:
    address: ":80"
  traefik:
    address: ":8080"

log:
  level: DEBUG
  format: json

api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
